"hi": 
  - What's up jackass?
"hello": 
  - How do you do. Please state your problem.
  - Nice to meet you. What brings you here today? 
"i want": 
  - What would it mean if you got REPLACEME?
  - Why do you want REPLACEME?
  - Suppose you got REPLACEME soon.
"if": 
  - Do you really think its likely that REPLACEME?
  - Do you wish that REPLACEME?
  - What do you think about REPLACEME?
  - Really? if REPLACEME?
"no": 
  - Why not?
  - You are being a bit negative.
  - Are you saying 'no' just to be negative?
"computer":  
  - Do computers worry you?
  - What do you think about machines?
  - Why do you mention computers?
  - What do you think machines have to do with your problem?
"name":
  - I am not interested in names
"sorry":
  - Please don't apologize
  - Apologies are not necessary
  - What feelings do you have when you apologize
"i was":
  - Were you really?
  - Perhaps I already knew you were REPLACEME.
  - Why do you tell me you were REPLACEME now?
  - How long were you REPLACEME for?
"i feel":
  - Do you often feel REPLACEME?
"i have":
  - How long have you had REPLACEME?
"i am":
  - How long have you been REPLACEME?
"i felt":
  - How long have you felt REPLACEME?
  - What other feelings do you have?
"i remember":
  - Do you often think of REPLACEME?
  - Does thinking of REPLACEME bring anything else to mind?
  - What else do you remember?
  - Why do you recall REPLACEME right now?
  - What in the present situation reminds you of REPLACEME?
  - What is the connection between me and REPLACEME?
"do you remember":
  - Did you think I would forget REPLACEME?
  - Why do you think I should recall REPLACEME now?
  - What about REPLACEME?
  - You mentioned REPLACEME
"i dreamt":
  - "Really-- REPLACEME"
  - Have you ever fantasized REPLACEME while you were awake?
  - Have you dreamt REPLACEME before?
"dream about":   
  - How do you feel about REPLACEME in reality?
"dream":
  - What does this dream suggest to you?
  - Do you dream often?
  - What persons appear in your dreams?
  - Don't you believe that dream has to do with your problem?
"my mother":
  - Who else in your family REPLACEME?
  - Tell me more about your family
"my father":
  - Your father? 
  - Does he influence you strongly? 
  - What else comes to mind when you think of your father?
"i want":
  - What would it mean if you got REPLACEME
  - Why do you want REPLACEME Suppose you got REPLACEME soon
"i am glad": 
  - How have I helped you to be REPLACEME? 
  - What makes you happy just now
  - Can you explain why you are suddenly REPLACEME?
"i am sad":
  - I am sorry to hear you are depressed
  - I'm sure its not pleasant to be sad
"alike":
  - In what way? What similarities are there?
"same":
  - What other connections do you see?